### create user
POST express-js-production-5ad3.up.railway.app/api/v1/auth/register
Content-Type: application/json

{
    "first_name": "sabrina",
    "last_name": "binar",
    "email": "sabrina@gmail.com",
    "password": "123456"
}

### Login user
POST express-js-production-5ad3.up.railway.app/api/v1/auth/login
Content-Type: application/json

{
    "email": "sabrina@gmail.com",
    "password": "123456"
}

### verified login
GET express-js-production-5ad3.up.railway.app/api/v1/auth/authenticate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6InNhYnJpbmEiLCJsYXN0X25hbWUiOiJiaW5hciIsImVtYWlsIjoic2FicmluYUBnbWFpbC5jb20iLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQ4MjM5NjZ9.sqQzxA0tYO_3y75uwAkD3UlGXt2zqD5W3huLRFEukxc

### Get all user
GET express-js-production-5ad3.up.railway.app/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6InNhYnJpbmEiLCJsYXN0X25hbWUiOiJiaW5hciIsImVtYWlsIjoic2FicmluYUBnbWFpbC5jb20iLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQ4MjM5NjZ9.sqQzxA0tYO_3y75uwAkD3UlGXt2zqD5W3huLRFEukxc

### Get all user by search
GET express-js-production-5ad3.up.railway.app/api/v1/users?search=michael
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6Im1pY2hhZWwiLCJsYXN0X25hbWUiOiJqaG9uIiwiZW1haWwiOiJtaWNoYWVsakBnbWFpbC5jb20iLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQ1NDAxMjd9.z9ehYjy31BGm5nya1tA8ZM7chDruukWQVuzR1atqW-s

### Get user by id
GET http://localhost:3000/api/v1/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksIm5hbWUiOiJwb2tlIiwiZW1haWwiOiJwb2tlQGdtYWlsLmNvbSIsImlhdCI6MTcxMzcxNDE4NH0.rTMBaKCkfTD0oI5gm4l03JEqxzhH7LBpa0SLmUbMRIE

### Update profile
PUT http://localhost:3000/api/v1/users/3/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6Im1pY2hhZWwiLCJsYXN0X25hbWUiOiJqaG9uIiwiZW1haWwiOiJtaWNoYWVsakBnbWFpbC5jb20iLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQ1NDAxMjd9.z9ehYjy31BGm5nya1tA8ZM7chDruukWQVuzR1atqW-s
Content-Type: application/json

{
    "address" : "Jl. Soekarno Hatta X",
    "occupation" : "Student" 
}

### Delete 
DELETE  http://localhost:3000/api/v1/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6Im1pY2hhZWwiLCJsYXN0X25hbWUiOiJqaG9uIiwiZW1haWwiOiJtaWNoYWVsakBnbWFpbC5jb20iLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQ1NDAxMjd9.z9ehYjy31BGm5nya1tA8ZM7chDruukWQVuzR1atqW-s

### GET all picture
GET http://localhost:3000/api/v1/pictures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RfbmFtZSI6Im1pY2hhZWwiLCJsYXN0X25hbWUiOiJqaG9uIiwiZW1haWwiOiJtaWNoYWVsakBnbWFpbC5jb20iLCJhZGRyZXNzIjoiSmwuIE1lbnVqdSBTdXJnYSBYIiwib2NjdXBhdGlvbiI6IlNvZnR3YXJlIEVuZ2luZWVyIiwiYXZhdGFyX3VybCI6Imh0dHBzOi8vaWsuaW1hZ2VraXQuaW8vcml6a2lyb2Jhd2EvY2hhbGxlbmdlLTYvYXZhdGFycy8xNzE0NjIwNzcyOTI1X01YQkl0aXRvcC5wbmciLCJpYXQiOjE3MTQ2MjcwMjl9.qcul1_2ry6o6EgOXOULzXBCCzHfiOns8rJM-BSJcwok

### GET picture by id
GET http://localhost:3000/api/v1/pictures/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6Im1pY2hhZWwiLCJsYXN0X25hbWUiOiJqaG9uIiwiZW1haWwiOiJtaWNoYWVsakBnbWFpbC5jb20iLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQ1NDAxMjd9.z9ehYjy31BGm5nya1tA8ZM7chDruukWQVuzR1atqW-s

### Delete picture by id
DELETE http://localhost:3000/api/v1/pictures/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6Im1pY2hhZWwiLCJsYXN0X25hbWUiOiJqaG9uIiwiZW1haWwiOiJtaWNoYWVsakBnbWFpbC5jb20iLCJhZGRyZXNzIjpudWxsLCJvY2N1cGF0aW9uIjpudWxsLCJhdmF0YXJfdXJsIjpudWxsLCJpYXQiOjE3MTQ1NDAxMjd9.z9ehYjy31BGm5nya1tA8ZM7chDruukWQVuzR1atqW-s